"""empty message

Revision ID: a4195ec240ee
Revises: e19c98a546c5
Create Date: 2021-03-07 10:47:30.691183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4195ec240ee'
down_revision = 'e19c98a546c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'user_id')
    # ### end Alembic commands ###
